#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    s=s.capitalize()
    j=0
    d=s[0]
    for i in range(1,len(s)):
        
        if (s[i-1].isspace()==True):
            d=d+s[i].swapcase()
        else:
            d=d+s[i]
    return d

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
